// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarsFactoryWebAPI.Models
{
    public partial class CarsTable
    {
        public int IdCar { get; set; }
        public string Codigo { get; set; }
        public string Tipo { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Año { get; set; }
        public string Estado { get; set; }
        public decimal? Precio { get; set; }
        public byte[] Imagen { get; set; }
        public DateTime? FechaModificacion { get; set; }
    }
}